# Assembler section type character
#
ASM_TCHAR	:= %
ASM_TCHAR_OPS	:= %%

# Include common RISC-V headers
#
INCDIRS		+= arch/riscv/include

# RISC-V-specific directories containing source files
#
SRCDIRS		+= arch/riscv/interface/efi
